---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
    custom-label: custom-label-value
  name: cert-manager-cainjector
  namespace: cert-manager-tanzu-package
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    custom-label: custom-label-value
  name: cert-manager
  namespace: cert-manager-tanzu-package
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
    custom-label: custom-label-value
  name: cert-manager-webhook
  namespace: cert-manager-tanzu-package
