apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert-manager-certificate
spec:
  dnsNames:
  - cert-manager-cert-domain.example.com
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-clusterissuer
  secretName: test-cert-manager-secret
