apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: .
    helmChart:
      name: cert-manager
      version: v1.1.0
      repository:
        url: https://charts.jetstack.io

