apiVersion: install.package.carvel.dev/v1alpha1
kind: InstalledPackage
metadata:
  name: cert-manager.tce.vmware.com
  namespace: default
spec:
  packageRef:
    versionSelection:
      constraints: $(PACKAGE_VERSION)
      prereleases: {}
