---
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager.tce.vmware.com.1.1.0-vmware0
spec:
  description: This package provides certificate management functionality.
  publicName: cert-manager.tce.vmware.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: index.docker.io/benjvi/custom-package-repo-packages@sha256:488ec6fe8f93b0b001ab02202c6e209ca65b90a3a01cdaf604daffad85db67aa
      template:
      - ytt:
          ignoreUnknownComments: true
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 1.1.0-vmware0
---
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: velero.tce.vmware.com.1.5.2-vmware0
spec:
  description: This package provides disaster recovery capabilities.
  publicName: velero.tce.vmware.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: index.docker.io/benjvi/custom-package-repo-packages@sha256:31e9ba348815809540bec24c8eabfe04bc89f330c1e4da7da793e969f66d01cf
      template:
      - ytt:
          ignoreUnknownComments: true
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 1.5.2-vmware0
